type Query {
    recipe(id: ID): Recipe
    pid: Int
}

type Recipe {
    id: ID!
    name: String!
    steps: String
    ingredients: [Ingredients]!
}

type Ingredients {
    id: ID!
    name: String!
    quantity: String
}